let array = [
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5112,
        "CODITM": "MT56Z0W2          ",
        "CANTIDAD": 1,
        "PROVEEDOR": "MONTAGNE                 ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "OUTDOOR",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21811086,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5159,
        "CODITM": "2254340           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21813748,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5159,
        "CODITM": "B046327           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "DISTRINANDO SA (BIBI)    ",
        "RUBRO": "CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21813748,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5160,
        "CODITM": "2264010           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "FUTBOL",
        "TIPO": "FUTBOL 5",
        "NROTRANS": 21813794,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5923,
        "CODITM": "2264010           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "FUTBOL",
        "TIPO": "FUTBOL 5",
        "NROTRANS": 21813853,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "CB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 1059,
        "CODITM": "2264010           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "FUTBOL",
        "TIPO": "FUTBOL 5",
        "NROTRANS": 21817455,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5167,
        "CODITM": "C11016N           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "CROCS                    ",
        "RUBRO": "CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZUECO",
        "NROTRANS": 21817999,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5123,
        "CODITM": "C10001N           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "CROCS                    ",
        "RUBRO": "CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZUECO",
        "NROTRANS": 21818285,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6585,
        "CODITM": "MT20971           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "MONTAGNE                 ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "OUTDOOR",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21818745,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6585,
        "CODITM": "5561682           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "RIDER                    ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "NATACION",
        "TIPO": "OJOTA",
        "NROTRANS": 21818745,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5126,
        "CODITM": "5561631           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "RIDER                    ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "NATACION",
        "TIPO": "CHINELA",
        "NROTRANS": 21818879,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5173,
        "CODITM": "2256790           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21819062,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6594,
        "CODITM": "2516110           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21819971,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 5129,
        "CODITM": "2297700           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "TOPPER                   ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "RUNNING",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21820071,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6598,
        "CODITM": "9505776           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "UMBRO                    ",
        "RUBRO": "ACCESORIOS",
        "DISCIPLINA": "FUTBOL",
        "TIPO": "BOLSO",
        "NROTRANS": 21820702,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6598,
        "CODITM": "ATL0093           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "ATLET                    ",
        "RUBRO": "ACCESORIOS",
        "DISCIPLINA": "TRAINING",
        "TIPO": "MEDIAS",
        "NROTRANS": 21820702,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6600,
        "CODITM": "9505985           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "FILA                     ",
        "RUBRO": "DEPORTES CALZADO",
        "DISCIPLINA": "RUNNING",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21821146,
        "FECHA": "2022-11-01 00:00:00"
    },
    {
        "COD_VENDEDOR": "116",
        "CODCMP": "FB",
        "VENDEDOR": "ROSALES JAVIER ALBERTO                                      ",
        "CODSUC": 1,
        "NUMERO": 6601,
        "CODITM": "RIN0017           ",
        "CANTIDAD": 1,
        "PROVEEDOR": "RINGO                    ",
        "RUBRO": "CALZADO",
        "DISCIPLINA": "MODA",
        "TIPO": "ZAPATILLA",
        "NROTRANS": 21821397,
        "FECHA": "2022-11-01 00:00:00"
    }
]

console.table(array);

let unidades =  0
let arrayTrans = new Set()

array.forEach(e => {
    arrayTrans.add(e.NROTRANS)
});


console.log(arrayTrans);